# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

.before_script_template:
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install --upgrade pip

# 2 stages linting and test before we are generating a release
stages:
    - lint
    - test
    - prepare
    - release

prepare_job:
    stage: prepare
    image: alpine:latest
    rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
    script:
      - apk add curl jq
      - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
      - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" -X POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG"'
      - echo "Release-Notes:"
      - cat release_notes.md
    artifacts:
      paths:
        - "release_notes.md"

release_job:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    needs:
      - job: prepare_job
    rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
    script:
      - echo "Creating release"
    release:
      name: 'CPM-Downloader release $CI_COMMIT_TAG'
      description: release_notes.md
      tag_name: '$CI_COMMIT_TAG'
      ref: '$CI_COMMIT_SHA'
      assets:
        links:
          - name: 'Container Image $CI_COMMIT_TAG'
            url: "https://$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CI_COMMIT_SHA"

linting:
    extends: .before_script_template
    stage: lint
    script:
        - pylint --fail-under=8 --fail-on=E --ignore=test_*.py --errors-only --disable=C,R --output=pylint.txt *.py
    except:
      - tags
    artifacts:
      untracked: false
      when: always
      expire_in: 30 days
      paths:
        - "pylint.txt"

unittest:
    extends: .before_script_template
    stage: test
    script:
        - python3 ./venv/lib/python3.9/site-packages/pytest tests
    except:
      - tags
